# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DecFuzzer(object):
    def setupUi(self, DecFuzzer):
        DecFuzzer.setObjectName("DecFuzzer")
        DecFuzzer.resize(400, 300)
        self.label = QtWidgets.QLabel(DecFuzzer)
        self.label.setGeometry(QtCore.QRect(140, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(DecFuzzer)
        self.widget.setGeometry(QtCore.QRect(140, 90, 111, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(DecFuzzer)
        QtCore.QMetaObject.connectSlotsByName(DecFuzzer)

    def retranslateUi(self, DecFuzzer):
        _translate = QtCore.QCoreApplication.translate
        DecFuzzer.setWindowTitle(_translate("DecFuzzer", "Form"))
        self.label.setText(_translate("DecFuzzer", "DecFuzzer"))
        self.pushButton.setText(_translate("DecFuzzer", "run.py"))
        self.pushButton_2.setText(_translate("DecFuzzer", "reproduce.py"))
        self.pushButton_3.setText(_translate("DecFuzzer", "readme"))
