# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'run.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DecFuzzer(object):
    def setupUi(self, DecFuzzer):
        DecFuzzer.setObjectName("DecFuzzer")
        DecFuzzer.resize(400, 300)
        self.label = QtWidgets.QLabel(DecFuzzer)
        self.label.setGeometry(QtCore.QRect(20, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(DecFuzzer)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 251, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(DecFuzzer)
        self.layoutWidget.setGeometry(QtCore.QRect(264, 210, 124, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)

        self.retranslateUi(DecFuzzer)
        QtCore.QMetaObject.connectSlotsByName(DecFuzzer)

    def retranslateUi(self, DecFuzzer):
        _translate = QtCore.QCoreApplication.translate
        DecFuzzer.setWindowTitle(_translate("DecFuzzer", "Form"))
        self.label.setText(_translate("DecFuzzer", "run.py"))
        self.pushButton_5.setText(_translate("DecFuzzer", "Run the process"))
        self.pushButton_4.setText(_translate("DecFuzzer", "Stop the process"))
        self.pushButton_3.setText(_translate("DecFuzzer", "Return to main menu"))
